#!/usr/bin/env zsh
#
# Executes commands at the start of an interactive session.
#
# echo "zshrc - $PATH"
#
# Command history stuff
#
HISTFILE=${HOME}/.zsh_history
HISTSIZE=500
#
##############################################################################
#
# completions - https://stackoverflow.com/questions/26462667/git-completion-not-working-in-zsh-on-os-x-yosemite-with-homebrew#26479426
#
if [[ -d /usr/local/share/zsh-completions ]]; then
  fpath=(/usr/local/share/zsh-completions "${fpath[@]}")
fi
#
# if [[ -d /usr/local/share/zsh/site-functions ]]; then
#   fpath=(/usr/local/share/zsh/site-functions "${fpath[@]}")
# fi

# moar completions
if [[ -d "${HOME}/.zsh-functions" ]]; then
  fpath=(${HOME}/.zsh-functions "${fpath[@]}")
fi

if [[ -d "${HOME}/.dotfiles/zsh/completion.d" ]]; then
  fpath=(${HOME}/.dotfiles/zsh/completion.d "${fpath[@]}")
fi

autoload -U compinit && compinit
zmodload -i zsh/complist

#
##############################################################################
#
# zsh plugins
#
if [[ -d "${HOME}/.dotfiles/zsh/plugins/" ]]; then
  setopt EXTENDED_GLOB
  for plugin in "${HOME}"/.dotfiles/zsh/plugins/*; do
    # echo "$plugin"
    source "$plugin"/*.zsh
  done
fi

# I dunno - TextMate rbenv support maybe?
# if [ -d "${HOME}/.dotfiles/path/zz-ruby.sh" ]; then
#     source "${HOME}/.dotfiles/path/zz-ruby.sh"
# fi
#
##############################################################################
#
# iterm integration
#
if [[ -f "${HOME}/.dotfiles/zsh/iterm2_shell_integration.zsh" ]]; then
  source "${HOME}/.dotfiles/zsh/iterm2_shell_integration.zsh"
fi
#
##############################################################################
#
# powerline
#
powerline_dir="${HOME}/.dotfiles/powerline"
if [[ -d "${powerline_dir}" ]]; then

  # performance?
  if command -v powerline-daemon >/dev/null; then
    powerline-daemon -q
  fi

  in_path=$(echo "$PATH" | grep -c "${powerline_dir}")
  if [[ $in_path -le 0 ]]; then
    export PATH="${PATH}:${powerline_dir}/scripts"
    # this breaks python > 3.4 from a conflict with the selectors module
    # export PYTHONPATH="${PYTHONPATH}:${HOME}/.dotfiles/powerline/powerline:${HOME}/.dotfiles/powerline/powerline/lib"
  fi
  source "${HOME}/.dotfiles/powerline/powerline/bindings/zsh/powerline.zsh"
fi
#
##############################################################################
#
# zsh-syntax highlighting
#
if [[ -f "/usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh" ]]; then
  # export ZSH_HIGHLIGHT_HIGHLIGHTERS_DIR=/usr/local/share/zsh-syntax-highlighting/highlighters
  source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
fi
