#
# Executes commands at login pre-zshrc.
#

my_resize() {
  if [ -x $(which resize 2>/dev/null) ]; then
    eval `resize`
  fi
}

# Reset window info on resize
TRAPWINCH () {
  my_resize
}

my_resize

#
# Mac OS X stuff
#
if [[ "$(uname -s)" == "Darwin" ]]; then

    # look for keyboardservicesd
    launchctl stop com.apple.keyboardservicesd

    # look for photoanalysisd
    PHOTO_ANALYSISD_DISABLED=$(launchctl print-disabled gui/$UID | grep 'com.apple.photoanalysisd' | awk '{print $3}' 2>/dev/null)
    if [[ "${PHOTO_ANALYSISD_DISABLED}" == "false" ]]; then
        launchctl disable gui/$UID/com.apple.photoanalysisd
        launchctl kill -TERM gui/$UID/com.apple.photoanalysisd
    fi

    # disable smart quotes
    if [[ $(defaults read NSGlobalDomain NSAutomaticQuoteSubstitutionEnabled) -eq 1 ]]; then
        defaults write NSGlobalDomain NSAutomaticQuoteSubstitutionEnabled -bool false
    fi

    # disable emdash
    if [[ $(defaults read NSGlobalDomain NSAutomaticDashSubstitutionEnabled) -eq 1 ]]; then
        defaults write NSGlobalDomain NSAutomaticDashSubstitutionEnabled -bool false
    fi
fi

if [ -e "${HOME}/.dotfiles/alias/bash-like" ]; then
  . "${HOME}/.dotfiles/alias/bash-like"
fi

setopt EXTENDED_GLOB
if [ -d "${HOME}/.dotfiles/path" ]; then
  for X in "${HOME}"/.dotfiles/path/*.sh; do
    #echo "$X"
    . "${X}"
  done
fi
