#
# Executes commands at login pre-zshrc.
#
if [ -e "${HOME}/.dotfiles/alias/bash-like" ]; then
  . "${HOME}/.dotfiles/alias/bash-like"
fi

RC_EXPAND_PARAM=1
if [ -d "${HOME}/.dotfiles/path" ]; then
  for X in $(ls ${HOME}/.dotfiles/path/*.sh); do
    #echo "$X"
    . "${X}"
  done
fi


