#
# Executes commands at the start of an interactive session.
#

# Customize to your needs...
JAVA_HOME=$(/usr/libexec/java_home)

# completions
if [ -d /usr/local/share/zsh-completions ]; then
  fpath=(/usr/local/share/zsh-completions $fpath)
fi

# zsh plugins
if [ -d "${HOME}/.dotfiles/zsh/plugins/bd" ]; then
  . "${HOME}/.dotfiles/zsh/plugins/bd/bd.zsh"
fi

# powerline
if [ -d "${HOME}/.dotfiles/powerline" ]; then
  . "${HOME}/.dotfiles/powerline/powerline/bindings/zsh/powerline.zsh"
fi
