#
# Executes commands at the start of an interactive session.
#
# increase open file limit
ulimit -n 10240

# completions
if [ -d /usr/local/share/zsh-completions ]; then
  fpath=(/usr/local/share/zsh-completions $fpath)
fi

if [ -d /usr/local/share/zsh/site-functions ]; then
  fpath=(/usr/local/share/zsh/site-functions $fpath)
fi

# moar completions
if [ -d "${HOME}/.dotfiles/zsh/completion.d" ]; then
  fpath=(${HOME}/.dotfiles/zsh/completion.d $fpath)
fi

# zsh plugins
if [ -d "${HOME}/.dotfiles/zsh/plugins/bd" ]; then
  . "${HOME}/.dotfiles/zsh/plugins/bd/bd.zsh"
fi

# iterm integration
if [ -f "${HOME}/.dotfiles/zsh/iterm2_shell_integration.zsh" ]; then
  . "${HOME}/.dotfiles/zsh/iterm2_shell_integration.zsh"
fi

# powerline
if [ -d "${HOME}/.dotfiles/powerline" ]; then
  export PATH="$PATH:${HOME}/.dotfiles/powerline/scripts"
  export PYTHONPATH="${PYTHONPATH}:${HOME}/.dotfiles/powerline/powerline:${HOME}/.dotfiles/powerline/powerline/lib"
  . "${HOME}/.dotfiles/powerline/powerline/bindings/zsh/powerline.zsh"
fi
