#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
JAVA_HOME=$(/usr/libexec/java_home)

source ~/bin/ansiweather/ansiweather.plugin.zsh

# zsh-bd
. $HOME/.zsh/plugins/bd/bd.zsh

. ~/Devel/powerline/powerline/bindings/zsh/powerline.zsh
