if [ -e "${HOME}/.dotfiles/alias/bash-like" ]; then
  . "${HOME}/.dotfiles/alias/bash-like"
fi

if [ -d "${HOME}/.dotfiles/path" ]; then
  for X in "${HOME}/.dotfiles/path/*.sh"; do
    . "${X}"
  done
fi