if [ -r "${HOME}/.dotfiles/alias/bash-like" ]; then
  . "${HOME}/.dotfiles/alias/bash-like"
fi

if [ -d "${HOME}/.dotfiles/path" ]; then
  for X in "${HOME}"/.dotfiles/path/*.sh; do
    . "${X}"
  done
fi

# powerline
if [ -d "${HOME}/.dotfiles/powerline" ]; then
  . "${HOME}/.dotfiles/powerline/powerline/bindings/bash/powerline.sh"
fi
